"use client";

import type { ChatSession } from "./copilot-store";

/**
 * Downloads a string as a file in the user's browser.
 */
function triggerDownload(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Sanitize filename from title.
 */
function sanitizeFilename(title: string, ext: string): string {
  const base = title
    .replace(/[^a-zA-Z0-9_-]/g, "_")
    .replace(/_+/g, "_")
    .slice(0, 40)
    .trim() || "chat_session";
  return `${base}.${ext}`;
}

/**
 * Export full chat session as clean Markdown.
 */
export function exportToMarkdown(session: ChatSession): void {
  const dateStr = new Date(session.updatedAt).toLocaleString();
  let md = `# ${session.title}\n\n`;
  md += `*Generated by Tathyx Decision Intelligence Copilot*\n`;
  md += `*Date: ${dateStr}*\n\n`;
  md += `---\n\n`;

  session.turns.forEach((turn, idx) => {
    md += `## Turn ${idx + 1}: Query\n\n`;
    md += `> ${turn.query}\n\n`;
    md += `### Answer\n\n`;
    const answerText = turn.answer?.answer || "No answer recorded.";
    md += `${answerText}\n\n`;

    if (turn.evidence && turn.evidence.length > 0) {
      md += `### Grounded Sources & Evidence\n\n`;
      turn.evidence.forEach((item, sIdx) => {
        const title = item.section_path?.join(" › ") || item.document_id;
        md += `${sIdx + 1}. **${title}** (Page ${item.page_number || 1})\n`;
        md += `   - *Snippet*: "${item.snippet ? item.snippet.trim() : ""}"\n\n`;
      });
    }

    if (turn.modelName || turn.latencyMs) {
      md += `*Model: ${turn.modelName || "Primary"} | Latency: ${turn.latencyMs ? `${turn.latencyMs}ms` : "N/A"}*\n\n`;
    }
    md += `---\n\n`;
  });

  triggerDownload(md, sanitizeFilename(session.title, "md"), "text/markdown;charset=utf-8");
}

/**
 * Export full chat session as Microsoft Word (.doc / .docx compatible).
 */
export function exportToDocx(session: ChatSession): void {
  const dateStr = new Date(session.updatedAt).toLocaleString();
  let html = `
    <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
    <head>
      <meta charset='utf-8'>
      <title>${session.title}</title>
      <style>
        body { font-family: 'Calibri', 'Segoe UI', sans-serif; font-size: 11pt; line-height: 1.6; color: #1D1A18; margin: 40px; }
        h1 { color: #161514; font-size: 20pt; border-bottom: 2px solid #8F7240; padding-bottom: 6px; margin-bottom: 4px; }
        .meta { font-size: 9pt; color: #8E8273; margin-bottom: 24px; }
        .turn-box { background: #F3E8D6; border: 1px solid #E6D5BD; border-radius: 8px; padding: 16px; margin-bottom: 20px; }
        .query-label { font-size: 9pt; font-weight: bold; color: #8F7240; text-transform: uppercase; margin-bottom: 4px; }
        .query { font-size: 13pt; font-weight: 600; color: #161514; margin-bottom: 12px; }
        .answer { font-size: 11pt; color: #3A3530; line-height: 1.7; margin-bottom: 16px; }
        .sources-title { font-size: 10pt; font-weight: bold; color: #4A433D; border-top: 1px solid #CFC0A9; padding-top: 10px; margin-top: 14px; }
        .source-item { font-size: 9.5pt; color: #4A433D; margin-bottom: 8px; }
        .source-badge { font-family: monospace; font-size: 8.5pt; background: #F3E8D6; color: #6E5832; padding: 2px 6px; border-radius: 4px; }
      </style>
    </head>
    <body>
      <h1>${session.title}</h1>
      <div class="meta">Tathyx Decision Intelligence Report · Generated: ${dateStr}</div>
  `;

  session.turns.forEach((turn, idx) => {
    const answerText = (turn.answer?.answer || "")
      .replace(/\n\n/g, "</p><p>")
      .replace(/\n/g, "<br/>");

    html += `
      <div class="turn-box">
        <div class="query-label">Question ${idx + 1}</div>
        <div class="query">${turn.query}</div>
        <div class="answer"><p>${answerText}</p></div>
    `;

    if (turn.evidence && turn.evidence.length > 0) {
      html += `<div class="sources-title">Grounded Evidence Sources:</div>`;
      turn.evidence.forEach((ev, sIdx) => {
        const title = ev.section_path?.join(" › ") || ev.document_id;
        html += `
          <div class="source-item">
            <span class="source-badge">[Source ${sIdx + 1}]</span>
            <strong>${title}</strong> (Page ${ev.page_number || 1})
            <div><em>"${(ev.snippet || "").slice(0, 200)}..."</em></div>
          </div>
        `;
      });
    }

    html += `</div>`;
  });

  html += `</body></html>`;

  triggerDownload(html, sanitizeFilename(session.title, "doc"), "application/msword");
}

/**
 * Print-ready layout triggering the browser's PDF export dialog.
 */
export function exportToPdf(session: ChatSession): void {
  const printWindow = window.open("", "_blank");
  if (!printWindow) {
    alert("Please allow popups to generate the PDF print preview.");
    return;
  }

  const dateStr = new Date(session.updatedAt).toLocaleString();

  let turnsHtml = "";
  session.turns.forEach((turn, idx) => {
    const answerHtml = (turn.answer?.answer || "")
      .replace(/\n\n/g, "</p><p>")
      .replace(/\n/g, "<br/>");

    let evidenceHtml = "";
    if (turn.evidence && turn.evidence.length > 0) {
      evidenceHtml += `<div class="evidence-block">
        <h4>Grounded Citations & Evidence</h4>
        <ol>`;
      turn.evidence.forEach((ev) => {
        const title = ev.section_path?.join(" › ") || ev.document_id;
        evidenceHtml += `<li>
          <strong>${title}</strong> (Page ${ev.page_number || 1})
          <p class="excerpt">"${(ev.snippet || "").trim()}"</p>
        </li>`;
      });
      evidenceHtml += `</ol></div>`;
    }

    turnsHtml += `
      <div class="turn">
        <div class="turn-header">Exchange ${idx + 1}</div>
        <h3 class="query">${turn.query}</h3>
        <div class="answer"><p>${answerHtml}</p></div>
        ${evidenceHtml}
        <div class="turn-footer">
          ${turn.modelName ? `<span>Model: ${turn.modelName}</span>` : ""}
          ${turn.latencyMs ? `<span>Latency: ${turn.latencyMs}ms</span>` : ""}
        </div>
      </div>
    `;
  });

  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
      <head>
        <title>${session.title} - Tathyx Intelligence Report</title>
        <style>
          @page { size: A4; margin: 20mm; }
          body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
            color: #1A1817;
            line-height: 1.6;
            margin: 0;
            padding: 0;
          }
          .header {
            border-bottom: 2px solid #B8924F;
            padding-bottom: 12px;
            margin-bottom: 24px;
          }
          .brand {
            font-size: 11px;
            font-weight: 700;
            letter-spacing: 1px;
            color: #B8924F;
            text-transform: uppercase;
          }
          h1 {
            font-size: 22px;
            margin: 6px 0 4px;
            color: #161514;
          }
          .date {
            font-size: 11px;
            color: #8E8273;
          }
          .turn {
            margin-bottom: 28px;
            padding-bottom: 20px;
            border-bottom: 1px solid #E6D5BD;
            page-break-inside: avoid;
          }
          .turn-header {
            font-size: 10px;
            font-weight: 700;
            color: #8E8273;
            text-transform: uppercase;
            letter-spacing: 0.5px;
          }
          .query {
            font-size: 15px;
            color: #161514;
            margin: 4px 0 12px;
          }
          .answer {
            font-size: 12px;
            color: #3A3530;
            line-height: 1.7;
          }
          .evidence-block {
            margin-top: 14px;
            padding: 12px;
            background: #F3E8D6;
            border-left: 3px solid #B8924F;
            border-radius: 4px;
          }
          .evidence-block h4 {
            margin: 0 0 8px;
            font-size: 11px;
            text-transform: uppercase;
            color: #4A433D;
          }
          .evidence-block ol {
            margin: 0;
            padding-left: 18px;
            font-size: 11px;
          }
          .evidence-block li {
            margin-bottom: 6px;
          }
          .excerpt {
            font-style: italic;
            color: #8E8273;
            margin: 2px 0 0;
          }
          .turn-footer {
            margin-top: 10px;
            font-size: 10px;
            color: #A99A86;
            display: flex;
            gap: 16px;
          }
        </style>
      </head>
      <body>
        <div class="header">
          <div class="brand">Tathyx Intelligence Platform</div>
          <h1>${session.title}</h1>
          <div class="date">Exported on ${dateStr}</div>
        </div>
        ${turnsHtml}
        <script>
          window.onload = function() {
            setTimeout(function() {
              window.print();
            }, 300);
          };
        </script>
      </body>
    </html>
  `);
  printWindow.document.close();
}

/**
 * Copy shareable link to clipboard.
 */
export async function copyShareLink(session: ChatSession): Promise<boolean> {
  try {
    const shareUrl = `${window.location.origin}/copilot?session=${session.id}`;
    if (navigator.clipboard?.writeText) {
      await navigator.clipboard.writeText(shareUrl);
      return true;
    }
    // Fallback
    const input = document.createElement("input");
    input.value = shareUrl;
    document.body.appendChild(input);
    input.select();
    document.execCommand("copy");
    document.body.removeChild(input);
    return true;
  } catch {
    return false;
  }
}
